server:
  port: 9040


spring:
  jpa:
    show-sql: true
  mvc:
    log-request-details: true

notepad:
  database:
    driver-class-name: org.postgresql.Driver
    database: notepad_db
    host: localhost
    port: 5432
    username: postgres
    password: postgres
